### ISSUE TITLE
Metaphors

### ISSUE THREAD

**Issue by exoer** [nilsnh/poetry-for-programmers#1]
How about to add a section about that thinking in terms of metaphors can be useful both in poetry and in programming.

**Comment by nilsnh** [comment]
It's a good point! Thank you for the suggestion. :) 

I tried to highlight this here: 8d9a40eb1af9869c2152549902b00ac13ccd30b9 . 

I'll close this issue for now. But feel free to reopen if you have an idea of some book or quote i could include on the [writing poetically](https://poetry-for-programmers.workshop.nilsnh.no/poetry/writing-poetically/) page.
